Repository iTechArt-RubyLab/movie-land, pull requests merged in 2022-03, with the labels that each got.

#34 ML-027/add person system
  Gemfile.lock
  app/models/actor_role.rb
  app/models/movie.rb
  app/models/movie_staff.rb
  app/models/person.rb
  db/migrate/20220222175108_create_actor_roles.rb
  db/migrate/20220222213807_create_movie_staffs.rb
  db/migrate/20220228000837_add_index_to_movie_staffs.rb
  db/migrate/20220228001558_add_index_to_actor_roles.rb
  db/migrate/20220228225040_add_index_to_staff_type.rb
  db/schema.rb
  spec/factories/people.rb
Labels: ready for mentors review

#45 ML-031/add policies specs
  Gemfile
  Gemfile.lock
  app/models/role.rb
  app/models/user.rb
  app/policies/base_entity_policy.rb
  db/seeds.rb
  spec/factories/permissions.rb
  spec/factories/roles.rb
  spec/factories/users.rb
  spec/policies/access_user_policy_spec.rb
  spec/policies/company_policy_spec.rb
  spec/policies/country_policy_spec.rb
  spec/policies/genre_policy_spec.rb
  spec/policies/language_policy_spec.rb
  spec/policies/movie_policy_spec.rb
  spec/policies/permission_policy_spec.rb
  spec/policies/person_policy_spec.rb
  spec/policies/rating_policy_spec.rb
  spec/policies/role_policy_spec.rb
  spec/policies/tag_policy_spec.rb
  spec/policies/user_policy_spec.rb
  spec/spec_helper.rb
Labels: approved

#46 ML-038/add error and status handling
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/application.rb
  lib/error/error_handler.rb
  lib/error/helpers/render.rb
Labels: ready for mentors review

#51 ML-041/add associations specs
  .rubocop.yml
  spec/factories/languages.rb
  spec/factories/people.rb
  spec/factories/ratings.rb
  spec/factories/tags.rb
  spec/models/company_spec.rb
  spec/models/country_spec.rb
  spec/models/genre_spec.rb
  spec/models/language_spec.rb
  spec/models/movie_spec.rb
  spec/models/permission_spec.rb
  spec/models/person_spec.rb
  spec/models/rating_spec.rb
  spec/models/role_spec.rb
  spec/models/tag_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/companies_spec.rb
  spec/requests/api/v1/country_spec.rb
  spec/requests/api/v1/genre_spec.rb
  spec/requests/api/v1/language_spec.rb
  spec/requests/api/v1/movie_spec.rb
  spec/requests/api/v1/permissions_spec.rb
  spec/requests/api/v1/person_spec.rb
  spec/requests/api/v1/roles_spec.rb
  spec/requests/api/v1/tags_spec.rb
  spec/routing/api/v1/companies_routing_spec.rb
  spec/routing/api/v1/countries_routing_spec.rb
  spec/routing/api/v1/genres_routing_spec.rb
  spec/routing/api/v1/languages_routing_spec.rb
  spec/routing/api/v1/movies_routing_spec.rb
  spec/routing/api/v1/people_routing_spec.rb
  spec/routing/api/v1/permissions_routing_spec.rb
  spec/routing/api/v1/roles_routing_spec.rb
  spec/routing/api/v1/tags_routing_spec.rb
Labels: approved

#44 ML-036/add view list
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/ratings_controller.rb
  app/controllers/api/v1/view_lists_controller.rb
  app/models/movie.rb
  app/models/rating.rb
  app/models/user.rb
  app/models/view_list.rb
  app/serializers/api/v1/movie_serializer.rb
  app/serializers/api/v1/user_serializer.rb
  app/serializers/api/v1/view_list_serializer.rb
  app/service/dictionary/find_service.rb
  app/service/person_service.rb
  app/service/rating_service.rb
  app/service/view_list_service.rb
  config/routes.rb
  db/migrate/20220225100111_create_view_lists.rb
  db/migrate/20220228090257_add_watching_status_to_view_lists.rb
  db/migrate/20220228182310_add_index_to_ratings.rb
  db/migrate/20220228183135_add_index_to_view_lists.rb
  db/schema.rb
  spec/factories/ratings.rb
  spec/factories/view_lists.rb
  spec/models/rating_spec.rb
  spec/models/view_list_spec.rb
  spec/routing/api/v1/ratings_routing_spec.rb
  spec/routing/api/v1/view_lists_routing_spec.rb
  spec/spec_helper.rb
Labels: ready for mentors review

#52 ML-040/add sidekiq
  .github/workflows/all.yml
  .gitignore
  Gemfile
  Gemfile.lock
  app/mailers/redactor_mailer.rb
  app/mailers/reviewer_mailer.rb
  app/service/notification/redactor_service.rb
  app/service/notification/reviewer_service.rb
  app/views/redactor_mailer/redactor_notification.html.erb
  app/views/redactor_mailer/redactor_notification.text.erb
  app/views/reviewer_mailer/reviewer_notification.html.erb
  app/views/reviewer_mailer/reviewer_notification.text.erb
  app/workers/redactor_notification_worker.rb
  app/workers/reviewer_notification_worker.rb
  config/application.rb
  config/environments/production.rb
  config/initializers/sidekiq.rb
  config/initializers/sidekiq_cron.rb
  config/routes.rb
  config/sidekiq.yml
  db/seeds.rb
  dump.rdb
  spec/factories/movies.rb
  spec/factories/ratings.rb
  spec/mailers/redactor_mailer_spec.rb
  spec/mailers/reviewer_mailer_spec.rb
  spec/requests/api/v1/movie_spec.rb
Labels: ready for mentors review, blocker

#49 ML-039/add carrierwave
  .gitignore
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/movies_controller.rb
  app/models/movie.rb
  app/models/permission.rb
  app/serializers/api/v1/movie_serializer.rb
  app/uploaders/image_uploader.rb
  app/uploaders/poster_uploader.rb
  config/initializers/carrierwave.rb
  db/migrate/20220301001851_add_poster_to_movies.rb
  db/migrate/20220301164517_add_images_to_movies.rb
  db/schema.rb
  spec/factories/movies.rb
  spec/factories/permissions.rb
  spec/fixtures/images/test.jpg
  spec/fixtures/images/test.svg
  spec/fixtures/posters/test.jpg
  spec/fixtures/posters/test.svg
  spec/models/movie_spec.rb
  spec/models/permission_spec.rb
  spec/spec_helper.rb
  spec/uploaders/image_uploader_spec.rb
  spec/uploaders/poster_uploader_spec.rb
Labels: approved

#57 ML-050/add specs for services
  spec/services/dictionary/find_service_spec.rb
  spec/services/guest_user_spec.rb
  spec/services/person_service_spec.rb
  spec/services/rating_service_spec.rb
  spec/services/view_list_service_spec.rb
Labels: approved

#53 ML-046/add comments
  app/controllers/api/v1/comments_controller.rb
  app/controllers/api/v1/permissions_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/models/comment.rb
  app/models/movie.rb
  app/models/permission.rb
  app/models/person.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/comment_policy.rb
  app/serializers/api/v1/comment_serializer.rb
  app/serializers/api/v1/movie_serializer.rb
  app/serializers/api/v1/permission_serializer.rb
  app/serializers/api/v1/person_serializer.rb
  config/routes.rb
  db/migrate/20220304184627_create_comments.rb
  db/migrate/20220304210200_add_can_leave_comment_to_permissions.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/comments.rb
  spec/factories/permissions.rb
  spec/models/comment_spec.rb
  spec/models/movie_spec.rb
  spec/models/permission_spec.rb
  spec/models/person_spec.rb
  spec/models/user_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/comments_spec.rb
  spec/routing/api/v1/comments_routing_spec.rb
Labels: approved

#48 ML-042/add elasticsearch
  .github/workflows/all.yml
  Gemfile
  Gemfile.lock
  app/controllers/home_controller.rb
  app/models/concerns/searchable.rb
  app/models/movie.rb
  config/kibana.yml
  config/routes.rb
Labels: ready for mentors review

#61 ML-045/add csv reports
  app/controllers/api/v1/movie_reports_controller.rb
  app/controllers/api/v1/permissions_controller.rb
  app/controllers/api/v1/person_reports_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/controllers/application_controller.rb
  app/models/permission.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/movie_report_policy.rb
  app/policies/person_report_policy.rb
  app/serializers/api/v1/permission_serializer.rb
  app/service/export/csv_generator_service.rb
  config/routes.rb
  db/migrate/20220308184336_add_can_export_to_csv_to_permissions.rb
  db/schema.rb
  spec/factories/permissions.rb
  spec/models/permission_spec.rb
  spec/models/user_spec.rb
  spec/policies/movie_report_policy_spec.rb
  spec/policies/person_report_policy_spec.rb
  spec/requests/api/v1/movie_reports_spec.rb
  spec/requests/api/v1/person_reports_spec.rb
  spec/routing/api/v1/movie_reports_routing_spec.rb
  spec/routing/api/v1/person_reports_routing_spec.rb
Labels: approved

#60 ML-052/fix n+1
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/awards_controller.rb
  app/controllers/api/v1/companies_controller.rb
  app/controllers/api/v1/countries_controller.rb
  app/controllers/api/v1/genres_controller.rb
  app/controllers/api/v1/languages_controller.rb
  app/controllers/api/v1/movies_controller.rb
  app/controllers/api/v1/people_controller.rb
  app/controllers/api/v1/ratings_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/api/v1/view_lists_controller.rb
  app/service/person_service.rb
  app/service/rating_service.rb
  app/service/view_list_service.rb
  app/services/application_service.rb
  app/services/dictionary/find_service.rb
  app/services/entity_manager/movie_service.rb
  app/services/entity_manager/person_service.rb
  app/services/entity_manager/rating_service.rb
  app/services/entity_manager/role_service.rb
  app/services/entity_manager/view_list_service.rb
  app/services/guest_user.rb
  app/services/notification/redactor_service.rb
  app/services/notification/reviewer_service.rb
  config/environments/development.rb
Labels: approved

#62 ML-053/add ratings calculation
  Gemfile.lock
  app/models/movie.rb
  app/models/rating.rb
  app/serializers/api/v1/movie_serializer.rb
  app/services/category_service.rb
  app/services/entity_manager/movie_service.rb
  app/services/export/csv_generator_service.rb
  app/services/movie_award_service.rb
  db/migrate/20220313030726_add_total_score_to_movies.rb
  db/migrate/20220313030945_add_number_of_ratings_to_movies.rb
  db/schema.rb
  spec/factories/movies.rb
  spec/models/movie_spec.rb
  spec/services/entity_manager/person_service_spec.rb
  spec/services/entity_manager/rating_service_spec.rb
  spec/services/entity_manager/view_list_service_spec.rb
Labels: ready for mentors review

#64 ML-056/improve specs
  db/seeds.rb
  spec/models/movie_spec.rb
  spec/models/role_spec.rb
  spec/policies/application_policy_spec.rb
  spec/policies/user_policy_spec.rb
  spec/spec_helper.rb
  spec/workers/redactor_notification_worker_spec.rb
  spec/workers/reviewer_notification_worker_spec.rb
Labels: approved

#63 ML-054/improvements
  app/controllers/api/v1/awards_controller.rb
  app/controllers/api/v1/categories_controller.rb
  app/controllers/api/v1/movie_awards_controller.rb
  app/controllers/api/v1/movies_controller.rb
  app/controllers/api/v1/people_controller.rb
  app/controllers/api/v1/ratings_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/controllers/api/v1/view_lists_controller.rb
  app/controllers/application_controller.rb
  app/models/role.rb
  app/policies/application_policy.rb
  app/serializers/api/v1/award_serializer.rb
  app/serializers/api/v1/category_serializer.rb
  app/serializers/api/v1/movie_award_serializer.rb
  app/serializers/api/v1/movie_serializer.rb
  app/serializers/api/v1/permission_serializer.rb
  app/serializers/api/v1/person_serializer.rb
  app/services/awards/find_service.rb
  app/services/categories/find_service.rb
  app/services/category_service.rb
  app/services/dictionary/find_service.rb
  app/services/entity_manager/movie_service.rb
  app/services/entity_manager/person_service.rb
  app/services/entity_manager/rating_service.rb
  app/services/entity_manager/role_service.rb
  app/services/entity_manager/view_list_service.rb
  app/services/guest_user.rb
  app/services/movie_award_service.rb
  app/services/movie_awards/find_service.rb
  app/services/movies/find_service.rb
  app/services/people/find_service.rb
  app/services/ratings/find_service.rb
  app/services/roles/find_service.rb
  app/services/users/guest.rb
  app/services/view_lists/find_service.rb
  lib/errors/error_handler.rb
  lib/errors/helpers/render.rb
  spec/services/people/find_service_spec.rb
  spec/services/ratings/find_service_spec.rb
  spec/services/users/guest_spec.rb
  spec/services/view_lists/find_service_spec.rb
Labels: ready for mentors review

#66 ML-044/add swagger
  .rubocop.yml
  app/controllers/api/v1/users_controller.rb
  config/routes.rb
  db/schema.rb
  spec/integration/auth_spec.rb
  spec/integration/awards_spec.rb
  spec/integration/categories_spec.rb
  spec/integration/comments_spec.rb
  spec/integration/companies_spec.rb
  spec/integration/countries_spec.rb
  spec/integration/genres_spec.rb
  spec/integration/languages_spec.rb
  spec/integration/movie_awards_spec.rb
  spec/integration/movie_report_spec.rb
  spec/integration/movies_spec.rb
  spec/integration/people_spec.rb
  spec/integration/permissions_spec.rb
  spec/integration/person_report_spec.rb
  spec/integration/ratings_spec.rb
  spec/integration/roles_spec.rb
  spec/integration/tags_spec.rb
  spec/integration/users_spec.rb
  spec/integration/view_lists_spec.rb
  spec/models/movie_award_spec.rb
  spec/models/movie_spec.rb
  spec/models/rating_spec.rb
  spec/models/view_list_spec.rb
  spec/policies/comment_policy_spec.rb
  spec/policies/movie_award_policy_spec.rb
  spec/policies/movie_policy_spec.rb
  spec/policies/movie_report_policy_spec.rb
  spec/policies/rating_policy_spec.rb
  spec/policies/view_list_policy_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/comments_spec.rb
  spec/requests/api/v1/movie_awards_spec.rb
  spec/requests/api/v1/movie_reports_spec.rb
  spec/requests/api/v1/movie_spec.rb
  spec/requests/api/v1/permissions_spec.rb
  spec/support/shared_contexts/integration_test.rb
  spec/support/shared_contexts/unique_generator.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: ready for mentors review

#65 ML-057/improve services specs
  spec/services/awards/find_service_spec.rb
  spec/services/categories/find_service_spec.rb
  spec/services/dictionary/find_service_spec.rb
  spec/services/movie_awards/find_service_spec.rb
  spec/services/movies/find_service_spec.rb
  spec/services/people/find_service_spec.rb
  spec/services/ratings/find_service_spec.rb
  spec/services/roles/find_service_spec.rb
  spec/services/users/guest_spec.rb
  spec/services/view_lists/find_service_spec.rb
Labels: ready for students review

#67 ML-055/improve elasticsearch
  app/controllers/api/v1/search_controller.rb
  app/controllers/home_controller.rb
  app/models/actor_role.rb
  app/models/concerns/searchable.rb
  app/models/movie.rb
  app/models/person.rb
  app/services/search/autocompleter.rb
  config/routes.rb
  lib/importers/elasticsearch_data.rb
  lib/tasks/elasticsearch_data_improter.rake
Labels: ready for students review

#68 ML-058/add elasticsearch specs
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/permissions_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/models/permission.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/search_policy.rb
  app/serializers/api/v1/permission_serializer.rb
  db/migrate/20220319074127_add_can_use_search_to_permissions.rb
  db/schema.rb
  spec/factories/permissions.rb
  spec/integration/categories_spec.rb
  spec/models/movie_spec.rb
  spec/models/permission_spec.rb
  spec/models/person_spec.rb
  spec/models/role_spec.rb
  spec/models/user_spec.rb
  spec/policies/search_policy_spec.rb
  spec/rails_helper.rb
  spec/routing/api/v1/search_routing_spec.rb
  spec/spec_helper.rb
Labels: approved

#69 ML-060/clean code
  app/models/actor_role.rb
  app/models/companies_movie.rb
  app/models/countries_movie.rb
  app/models/genres_movie.rb
  app/models/languages_movie.rb
  app/models/movie_award.rb
  app/models/movie_awards_person.rb
  app/models/movie_staff.rb
  app/models/movies_tag.rb
  app/models/person.rb
  app/models/rating.rb
  app/models/role.rb
  app/models/tag.rb
  app/models/user.rb
  app/policies/access_user_policy.rb
  app/policies/application_policy.rb
  app/policies/award_policy.rb
  app/policies/base_entity_policy.rb
  app/policies/category_policy.rb
  app/policies/comment_policy.rb
  app/policies/company_policy.rb
  app/policies/country_policy.rb
  app/policies/genre_policy.rb
  app/policies/language_policy.rb
  app/policies/movie_award_policy.rb
  app/policies/movie_policy.rb
  app/policies/movie_report_policy.rb
  app/policies/permission_policy.rb
  app/policies/person_policy.rb
  app/policies/person_report_policy.rb
  app/policies/rating_policy.rb
  app/policies/role_policy.rb
  app/policies/tag_policy.rb
  app/policies/user_policy.rb
  app/policies/view_list_policy.rb
  app/workers/redactor_notification_worker.rb
  app/workers/reviewer_notification_worker.rb
  db/seeds.rb
  swagger/v1/swagger.yaml
Labels: approved

#70 ML-061/improve swagger
  spec/integration/auth_spec.rb
  spec/integration/categories_spec.rb
  spec/integration/comments_spec.rb
  spec/integration/movie_awards_spec.rb
  spec/integration/movies_spec.rb
  spec/integration/people_spec.rb
  spec/integration/ratings_spec.rb
  spec/integration/users_spec.rb
  spec/integration/view_lists_spec.rb
  swagger/v1/swagger.yaml
Labels: approved

#71 ML-062/add readme
  README.md
  app/controllers/home_controller.rb
  spec/fixtures/banners/kitchen_mafia.jpg
  spec/fixtures/banners/movie_land.jpg
  spec/fixtures/database/schema.jpg
  spec/models/movie_spec.rb
Labels: ready for mentors review

#73 ML-064/add transaction to movie
  .rubocop.yml
  README.md
  app/controllers/api/v1/movies_controller.rb
Labels: ready for mentors review

#72 ML-063/improve heroku
  app/services/integration/the_movie_db.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: ready for mentors review
