Repository iTechArt-RubyLab/movie-land, pull requests merged in 2022-02, with the labels that each got.

#3 ML-003/add rubocop
  .rubocop.yml
  Gemfile
  Gemfile.lock
  Rakefile
Labels: Ready for review

#1 ML-001/Add gems
  .pryrc
  Gemfile
  Gemfile.lock
Labels: Ready for review

#6 ML-006/remove rubocop-performance
  .rubocop.yml
  Gemfile
  Gemfile.lock
Labels: approved

#11 ML-009/add genre
  app/models/genre.rb
  db/migrate/20220217160018_create_genres.rb
  db/schema.rb
  spec/factories/genres.rb
  spec/models/genre_spec.rb
Labels: Ready for review

#22 ML-020/rename title to name
  app/models/company.rb
  app/models/country.rb
  app/models/movie.rb
  db/migrate/20220219201606_change_to_name_for_title.rb
  db/schema.rb
  spec/factories/companies.rb
  spec/factories/countries.rb
  spec/factories/movies.rb
  spec/models/company_spec.rb
  spec/models/country_spec.rb
  spec/models/movie_spec.rb
Labels: approved

#21 ML-018/add country controller
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/countries_controller.rb
  app/serializers/api/v1/dictionary_serializer.rb
  app/service/dictionary/find_service.rb
  config/initializers/will_paginate.rb
  config/routes.rb
  db/seeds.rb
  spec/requests/api/v1/country_spec.rb
  spec/routing/api/v1/countries_routing_spec.rb
Labels: Ready for review

#23 ML-022/add company controller
  app/controllers/api/v1/companies_controller.rb
  app/service/dictionary/find_service.rb
  config/routes.rb
  db/seeds.rb
  spec/requests/api/v1/companies_spec.rb
  spec/routing/api/v1/companies_routing_spec.rb
Labels: Ready for review

#24 ML-021/add genre controller
  app/controllers/api/v1/genres_controller.rb
  config/routes.rb
  db/seeds.rb
  spec/requests/api/v1/genre_spec.rb
  spec/routing/api/v1/genres_routing_spec.rb
Labels: Ready for review

#12 ML-011/add language
  app/controllers/api/v1/languages_controller.rb
  app/models/language.rb
  config/routes.rb
  db/migrate/20220217162207_create_languages.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/languages.rb
  spec/models/language_spec.rb
  spec/requests/api/v1/language_spec.rb
  spec/routing/api/v1/languages_routing_spec.rb
Labels: Ready for review

#25 ML-023/add movie controller
  .gitignore
  app/controllers/api/v1/movies_controller.rb
  app/models/companies_movie.rb
  app/models/company.rb
  app/models/countries_movie.rb
  app/models/country.rb
  app/models/genre.rb
  app/models/genres_movie.rb
  app/models/language.rb
  app/models/languages_movie.rb
  app/models/movie.rb
  app/serializers/api/v1/movie_serializer.rb
  config/routes.rb
  db/migrate/20220220114730_create_join_table_countries_movies.rb
  db/migrate/20220220114747_create_join_table_genres_movies.rb
  db/migrate/20220220114804_create_join_table_companies_movies.rb
  db/migrate/20220220145356_create_join_table_languages_movies.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/movies.rb
  spec/requests/api/v1/movie_spec.rb
  spec/routing/api/v1/movies_routing_spec.rb
Labels: approved

#17 ML-015/add person
  app/controllers/api/v1/people_controller.rb
  app/models/country.rb
  app/models/person.rb
  app/serializers/api/v1/person_serializer.rb
  app/service/person_service.rb
  config/routes.rb
  db/migrate/20220218063503_create_people.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/people.rb
  spec/models/person_spec.rb
  spec/requests/api/v1/person_spec.rb
  spec/routing/api/v1/people_routing_spec.rb
Labels: Ready for review

#27 ML-017/add authentication
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  config/environments/development.rb
  config/initializers/cors.rb
  config/initializers/devise.rb
  config/initializers/devise_token_auth.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20220220190037_devise_token_auth_create_users.rb
  db/schema.rb
Labels: Ready for review

#8 ML-007/add tag
  Gemfile
  Gemfile.lock
  app/controllers/api/v1/tags_controller.rb
  app/models/movie.rb
  app/models/movies_tag.rb
  app/models/tag.rb
  app/serializers/api/v1/movie_serializer.rb
  config/routes.rb
  db/migrate/20220217151147_create_tags.rb
  db/migrate/20220221103431_create_join_table_movies_tags.rb
  db/migrate/20220222134656_add_index_to_tag.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/tags.rb
  spec/models/tag_spec.rb
  spec/rails_helper.rb
  spec/requests/api/v1/tags_spec.rb
  spec/routing/api/v1/tags_routing_spec.rb
Labels: approved

#31 ML-026/fix validations on database level
  Gemfile
  Gemfile.lock
  app/models/companies_movie.rb
  app/models/company.rb
  app/models/countries_movie.rb
  app/models/country.rb
  app/models/genre.rb
  app/models/genres_movie.rb
  app/models/language.rb
  app/models/languages_movie.rb
  app/models/movie.rb
  config/initializers/strong_migrations.rb
  db/migrate/20220220114730_create_join_table_countries_movies.rb
  db/migrate/20220220114747_create_join_table_genres_movies.rb
  db/migrate/20220220114804_create_join_table_companies_movies.rb
  db/migrate/20220220145356_create_join_table_languages_movies.rb
  db/migrate/20220221234643_add_index_to_role.rb
  db/migrate/20220222135646_add_index_to_tables.rb
  db/schema.rb
  spec/factories/companies.rb
  spec/factories/countries.rb
  spec/factories/genres.rb
  spec/factories/languages.rb
  spec/factories/movies.rb
  spec/models/company_spec.rb
  spec/models/country_spec.rb
  spec/models/genre_spec.rb
  spec/models/language_spec.rb
  spec/models/movie_spec.rb
Labels: approved

#37 ML-030/fix annotate
  Gemfile
  app/models/companies_movie.rb
  app/models/company.rb
  app/models/countries_movie.rb
  app/models/country.rb
  app/models/genre.rb
  app/models/genres_movie.rb
  app/models/language.rb
  app/models/languages_movie.rb
  app/models/movie.rb
  app/models/movies_tag.rb
  app/models/permission.rb
  app/models/person.rb
  app/models/role.rb
  app/models/tag.rb
  app/models/user.rb
  lib/tasks/auto_annotate_models.rake
  spec/factories/companies.rb
  spec/factories/countries.rb
  spec/factories/genres.rb
  spec/factories/languages.rb
  spec/factories/movies.rb
  spec/factories/people.rb
  spec/factories/tags.rb
  spec/models/company_spec.rb
  spec/models/country_spec.rb
  spec/models/genre_spec.rb
  spec/models/language_spec.rb
  spec/models/movie_spec.rb
  spec/models/person_spec.rb
  spec/models/tag_spec.rb
Labels: approved

#38 ML-030/fix index to tag migration
  db/migrate/20220222134656_add_index_to_tag.rb
Labels: ready for mentors review

#42 ML-035/organize controllers
  app/controllers/api/v1/companies_controller.rb
  app/controllers/api/v1/countries_controller.rb
  app/controllers/api/v1/genres_controller.rb
  app/controllers/api/v1/languages_controller.rb
  app/controllers/api/v1/movies_controller.rb
  app/controllers/api/v1/permissions_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/controllers/api/v1/tags_controller.rb
  app/controllers/home_controller.rb
  app/models/movie.rb
  app/models/movies_tag.rb
  config/routes.rb
  spec/requests/api/v1/companies_spec.rb
  spec/requests/api/v1/country_spec.rb
  spec/requests/api/v1/genre_spec.rb
  spec/requests/api/v1/language_spec.rb
  spec/requests/api/v1/tags_spec.rb
  spec/routing/api/v1/companies_routing_spec.rb
  spec/routing/api/v1/countries_routing_spec.rb
  spec/routing/api/v1/genres_routing_spec.rb
  spec/routing/api/v1/languages_routing_spec.rb
  spec/routing/api/v1/tags_routing_spec.rb
Labels: ready for mentors review, blocker

#43 ML-034/improve role system
  .rubocop.yml
  app/controllers/api/v1/movies_controller.rb
  app/controllers/api/v1/permissions_controller.rb
  app/controllers/api/v1/roles_controller.rb
  app/models/permission.rb
  app/models/role.rb
  app/models/user.rb
  app/policies/access_user_policy.rb
  app/policies/base_entity_policy.rb
  app/policies/base_policy.rb
  app/policies/company_policy.rb
  app/policies/country_policy.rb
  app/policies/genre_policy.rb
  app/policies/language_policy.rb
  app/policies/movie_policy.rb
  app/policies/permission_policy.rb
  app/policies/person_policy.rb
  app/policies/rating_policy.rb
  app/policies/role_policy.rb
  app/policies/tag_policy.rb
  app/policies/user_policy.rb
  app/serializers/api/v1/permission_serializer.rb
  app/serializers/api/v1/role_serializer.rb
  app/service/person_service.rb
  db/migrate/20220225100718_add_can_read_entities_to_permissions.rb
  db/migrate/20220225100956_add_can_edit_entities_to_permissions.rb
  db/migrate/20220226070912_remove_can_read_from_permissions.rb
  db/migrate/20220226070918_remove_can_edit_from_permissions.rb
  db/migrate/20220228182320_add_can_edit_permission_to_permissions.rb
  db/migrate/20220228183742_add_can_read_user_to_permissions.rb
  db/migrate/20220228210303_add_can_read_movie_to_permissions.rb
  db/migrate/20220228210316_add_can_edit_movie_to_permissions.rb
  db/migrate/20220228210331_add_can_read_person_to_permissions.rb
  db/migrate/20220228210343_add_can_edit_person_to_permissions.rb
  db/migrate/20220228211528_add_can_give_rating_to_permissions.rb
  db/migrate/20220228211548_add_can_read_rating_to_permissions.rb
  db/schema.rb
  db/seeds.rb
Labels: ready for students review, ready for mentors review
